### ISSUE TITLE
Make sidekiq workers configurable

### ISSUE THREAD

**Issue by digitalbuddha** [codechem/helm#8]
Hello, thank you for the fantastic mastodon chart. I wanted to ask if it would be possible to configure which queues are on the sidekiq replicas. Per the offical doc, there should only be 1 scheduler queue https://docs.joinmastodon.org/admin/scaling/

I believe this command does it 
```bundle exec sidekiq -q default -q pull -q push -q ingress -c 15```

**Comment by digitalbuddha** [comment]
After looking into this a bit more - I think the issue is that this chart depends on 4.0.2 

It seems like the latest docker image official chart had some changes allowing configuration of what queues go on what sidekiq replica

Could you possibly update to latest?

**Comment by digitalbuddha** [comment]
bit more info - this is what the config looks like when using the official chart

```
sidekiq:
    # -- Pod security context for all Sidekiq Pods, overwrites .Values.podSecurityContext
    podSecurityContext: {}
    # -- (Sidekiq Container) Security Context for all Pods, overwrites .Values.securityContext
    securityContext: {}
    # -- Resources for all Sidekiq Deployments unless overwritten
    resources: {}
    # -- Affinity for all Sidekiq Deployments unless overwritten, overwrites .Values.affinity
    affinity: {}
    # limits:
    #   cpu: "1"
    #   memory: 768Mi
    # requests:
    #   cpu: 250m
    #   memory: 512Mi
    workers:
    - name: all-queues
      # -- Number of threads / parallel sidekiq jobs that are executed per Pod
      concurrency: 25
      # -- Number of Pod replicas deployed by the Deployment
      replicas: 1
      # -- Resources for this specific deployment to allow optimised scaling, overwrites .Values.mastodon.sidekiq.resources
      resources: {}
      # -- Affinity for this specific deployment, overwrites .Values.affinity and .Values.mastodon.sidekiq.affinity
      affinity: {}
      # -- Sidekiq queues for Mastodon that are handled by this worker. See https://docs.joinmastodon.org/admin/scaling/#concurrency
      # See https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues for how to weight queues as argument
      queues:
        - default,8
        - push,6
        - ingress,4
        - mailers,2
        - pull
        - scheduler # Make sure the scheduler queue only exists once and with a worker that has 1 replica.
    - name: all-queues2
      concurrency: 25
      resources: {}
      replicas: 1
      queues:
        - default, 8
        - push, 6
        - ingress, 4
        - mailers, 2
        - pull
        ```
